name: ai_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^3.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  package_info_plus: ^5.0.1
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  screenshot: ^2.1.0
  share_plus: ^7.2.2
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  flutter_gemini: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8

  flutter_lints: ^2.0.0
  freezed: ^2.4.6

flutter:

  uses-material-design: true


  assets:
    - assets/lottie/
    - assets/images/
    - assets/svg/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
#          weight: 400
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
