// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8JeQyqpm5g_PaJjLvbJE6Rd2tks4JcDA',
    appId: '1:363975990498:android:a5e7fbfd1d32d0374212bb',
    messagingSenderId: '363975990498',
    projectId: 'ai-project-2d1fe',
    databaseURL: 'https://ai-project-2d1fe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ai-project-2d1fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVOdxKo_wW_rYqEejkhZFknnaW8qOe_vk',
    appId: '1:363975990498:ios:90a1d965d73bbd284212bb',
    messagingSenderId: '363975990498',
    projectId: 'ai-project-2d1fe',
    databaseURL: 'https://ai-project-2d1fe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ai-project-2d1fe.appspot.com',
    iosClientId: '363975990498-2j1ca1rushgn43mdi58kr8r2f20hkko7.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiProject',
  );
}
